/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "branch_id",
		label: "Select Branch",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "branch_target_id",
		label: "Select Branch Target",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "transaction_category_id",
		label: "Select Transaction Category",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "target_amount",
		label: "Enter Target Amount",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "fulfilled_amount",
		label: "Enter Fulfilled Amount",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "remaining_amount",
		label: "Enter Remaining Amount",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "requested_waiver_amount",
		label: "Enter Requested Waiver Amount",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "reason",
		label: "Enter Reason",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "application_status",
		label: "Select Application Status",
		type: "select",
		label: "Select Application Status",
		multiple: false,
		data_list: [
			{ label: "Pending", value: "pending" },
			{ label: "Approved", value: "approved" },
			{ label: "Rejected", value: "rejected" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "approved_waiver_amount",
		label: "Enter Approved Waiver Amount",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "reviewed_by",
		label: "Enter Reviewed By",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "reviewed_at",
		label: "Enter Reviewed At",
		type: "datetime-local",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "review_comment",
		label: "Enter Review Comment",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
