/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "account_id",
		label: "Select Account",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "type",
		label: "Select Type",
		type: "select",
		label: "Select Type",
		multiple: false,
		data_list: [
			{ label: "Income", value: "income" },
			{ label: "Expense", value: "expense" },
			{ label: "Investment", value: "investment" },
			{ label: "Withdrawal", value: "withdrawal" },
			{ label: "Transfer_in", value: "transfer_in" },
			{ label: "Transfer_out", value: "transfer_out" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "direction",
		label: "Select Direction",
		type: "select",
		label: "Select Direction",
		multiple: false,
		data_list: [
			{ label: "Credit", value: "credit" },
			{ label: "Debit", value: "debit" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "amount",
		label: "Enter Amount",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "balance_before",
		label: "Enter Balance Before",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "balance_after",
		label: "Enter Balance After",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "reference_type",
		label: "Enter Reference Type",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "reference_id",
		label: "Select Reference",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "description",
		label: "Enter Description",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "product_id",
		label: "Select Product",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "investor_id",
		label: "Select Investor",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "transaction_date",
		label: "Enter Transaction Date",
		type: "date",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "created_by",
		label: "Enter Created By",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
