/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "badge_text",
		label: "Enter Badge Text",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "headline",
		label: "Enter Headline",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "subheadline",
		label: "Enter Subheadline",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "description",
		label: "Enter Description",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "primary_button_text",
		label: "Enter Primary Button Text",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "primary_button_url",
		label: "Enter Primary Button Url",
		type: "url",
		placeholder: "https://example.com",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "secondary_button_text",
		label: "Enter Secondary Button Text",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "secondary_button_url",
		label: "Enter Secondary Button Url",
		type: "url",
		placeholder: "https://example.com",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "media_type",
		label: "Select Media Type",
		type: "select",
		label: "Select Media Type",
		multiple: false,
		data_list: [
			{ label: "Image", value: "image" },
			{ label: "Video", value: "video" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "background_image",
		label: "Upload Background Image",
		type: "file",
		multiple: false,
		accept: "image/*",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "hero_image",
		label: "Upload Hero Image",
		type: "file",
		multiple: false,
		accept: "image/*",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "video_url",
		label: "Enter Video Url",
		type: "url",
		placeholder: "https://example.com",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "is_active",
		label: "Select Is Active",
		type: "select",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "1" },
			{ label: "No", value: "0" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
