/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "todo_group_id",
		label: "Select Todo Group",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "title",
		label: "Enter Title",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "assigned_to",
		label: "Enter Assigned To",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "estimated_days",
		label: "Enter Estimated Days",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "daily_rate",
		label: "Enter Daily Rate",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "fixed_cost",
		label: "Enter Fixed Cost",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "item_cost",
		label: "Enter Item Cost",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "is_recurring",
		label: "Select Is Recurring",
		type: "select",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "1" },
			{ label: "No", value: "0" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "priority",
		label: "Select Priority",
		type: "select",
		label: "Select Priority",
		multiple: false,
		data_list: [
			{ label: "Critical", value: "critical" },
			{ label: "High", value: "high" },
			{ label: "Medium", value: "medium" },
			{ label: "Low", value: "low" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "status",
		label: "Select Status",
		type: "select",
		label: "Select Status",
		multiple: false,
		data_list: [
			{ label: "Pending", value: "pending" },
			{ label: "In_progress", value: "in_progress" },
			{ label: "Completed", value: "completed" },
			{ label: "Skipped", value: "skipped" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "completed_at",
		label: "Enter Completed At",
		type: "date",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "note",
		label: "Enter Note",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "sort_order",
		label: "Enter Sort Order",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
