/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "month",
		label: "Enter Month",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "total_amount",
		label: "Enter Total Amount",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "sheet_status",
		label: "Select Sheet Status",
		type: "select",
		label: "Select Sheet Status",
		multiple: false,
		data_list: [
			{ label: "Draft", value: "draft" },
			{ label: "Finalized", value: "finalized" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "generated_by",
		label: "Enter Generated By",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "transaction_log_id",
		label: "Select Transaction Log",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
