/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "voucher_audit_id",
		label: "Select Voucher Audit",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "voucher_type",
		label: "Select Voucher Type",
		type: "select",
		label: "Select Voucher Type",
		multiple: false,
		data_list: [
			{ label: "Income", value: "income" },
			{ label: "Expense", value: "expense" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "voucher_id",
		label: "Select Voucher",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "income_verified",
		label: "Select Income Verified",
		type: "select",
		label: "Select Income Verified",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "yes" },
			{ label: "No", value: "no" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "expense_verified",
		label: "Select Expense Verified",
		type: "select",
		label: "Select Expense Verified",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "yes" },
			{ label: "No", value: "no" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "document_verified",
		label: "Select Document Verified",
		type: "select",
		label: "Select Document Verified",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "yes" },
			{ label: "No", value: "no" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "approval_history_verified",
		label: "Select Approval History Verified",
		type: "select",
		label: "Select Approval History Verified",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "yes" },
			{ label: "No", value: "no" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "related_record_verified",
		label: "Select Related Record Verified",
		type: "select",
		label: "Select Related Record Verified",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "yes" },
			{ label: "No", value: "no" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "is_ok",
		label: "Select Is Ok",
		type: "select",
		label: "Select Is Ok",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "yes" },
			{ label: "No", value: "no" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "comment",
		label: "Enter Comment",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "audited_by",
		label: "Enter Audited By",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "audited_at",
		label: "Enter Audited At",
		type: "datetime-local",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
