/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "order_number",
		label: "Enter Order Number",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "product_id",
		label: "Select Product",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "customer_id",
		label: "Select Customer",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "plan_name",
		label: "Enter Plan Name",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "billing_cycle",
		label: "Select Billing Cycle",
		type: "select",
		label: "Select Billing Cycle",
		multiple: false,
		data_list: [
			{ label: "Monthly", value: "monthly" },
			{ label: "Yearly", value: "yearly" },
			{ label: "One_time", value: "one_time" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "status",
		label: "Select Status",
		type: "select",
		label: "Select Status",
		multiple: false,
		data_list: [
			{ label: "Pending_payment", value: "pending_payment" },
			{ label: "Payment_submitted", value: "payment_submitted" },
			{ label: "Payment_verified", value: "payment_verified" },
			{ label: "Access_sent", value: "access_sent" },
			{ label: "Cancelled", value: "cancelled" },
			{ label: "Refunded", value: "refunded" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "delivery_method",
		label: "Select Delivery Method",
		type: "select",
		label: "Select Delivery Method",
		multiple: false,
		data_list: [
			{ label: "Email", value: "email" },
			{ label: "Manual_contact", value: "manual_contact" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "subtotal",
		label: "Enter Subtotal",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "discount_amount",
		label: "Enter Discount Amount",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "total_amount",
		label: "Enter Total Amount",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "coupon_code",
		label: "Enter Coupon Code",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "customer_note",
		label: "Enter Customer Note",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "ordered_at",
		label: "Enter Ordered At",
		type: "datetime-local",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "payment_verified_at",
		label: "Enter Payment Verified At",
		type: "datetime-local",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "access_sent_at",
		label: "Enter Access Sent At",
		type: "datetime-local",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "cancelled_at",
		label: "Enter Cancelled At",
		type: "datetime-local",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "created_by",
		label: "Enter Created By",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
