export default [
    // ── Customer Information ──────────────────────────────────────────────────
    {
        name: "customer_name",
        label: "Customer Name",
        type: "text",
        value: "",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "customer_phone",
        label: "Customer Phone",
        type: "text",
        value: "",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "customer_email",
        label: "Customer Email",
        type: "email",
        value: "",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "domain_name",
        label: "Domain Name",
        type: "text",
        value: "",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "preferred_delivery_date",
        label: "Preferred Delivery Date",
        type: "date",
        value: "",
        is_visible: true,
        class: "col-md-6",
    },

    // ── Product / Plan ────────────────────────────────────────────────────────
    {
        name: "product_id",
        label: "Product",
        type: "select",
        multiple: false,
        data_list: [],
        value: "",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "product_name",
        label: "Product Name (snapshot)",
        type: "text",
        value: "",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "plan_name",
        label: "Plan Name",
        type: "text",
        value: "",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "billing_cycle",
        label: "Billing Cycle",
        type: "select",
        multiple: false,
        data_list: [
            { label: "One Time", value: "one_time" },
            { label: "Monthly",  value: "monthly"  },
            { label: "Yearly",   value: "yearly"   },
        ],
        value: "one_time",
        is_visible: true,
        class: "col-md-6",
    },

    // ── Pricing ───────────────────────────────────────────────────────────────
    {
        name: "subtotal",
        label: "Subtotal",
        type: "number",
        step: "0.01",
        value: "",
        is_visible: true,
        class: "col-md-4",
    },
    {
        name: "discount_amount",
        label: "Discount Amount",
        type: "number",
        step: "0.01",
        value: "",
        is_visible: true,
        class: "col-md-4",
    },
    {
        name: "total_amount",
        label: "Total Amount",
        type: "number",
        step: "0.01",
        value: "",
        is_visible: true,
        class: "col-md-4",
    },
    {
        name: "coupon_code",
        label: "Coupon Code",
        type: "text",
        value: "",
        is_visible: true,
        class: "col-md-6",
    },

    // ── Payment ───────────────────────────────────────────────────────────────
    {
        name: "pay_now",
        label: "Customer Paid Now",
        type: "select",
        multiple: false,
        data_list: [
            { label: "No — Pay Later", value: "0" },
            { label: "Yes — Paid Now", value: "1" },
        ],
        value: "0",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "payment_method",
        label: "Payment Method",
        type: "select",
        multiple: false,
        data_list: [
            { label: "bKash",            value: "bkash"  },
            { label: "Nagad",            value: "nagad"  },
            { label: "Rocket",           value: "rocket" },
            { label: "Bank Transfer",    value: "bank"   },
            { label: "Card",             value: "card"   },
            { label: "Cash on Delivery", value: "cod"    },
        ],
        value: "",
        is_visible: true,
        class: "col-md-6",
    },

    // ── Order & Delivery Status ───────────────────────────────────────────────
    {
        name: "order_status",
        label: "Order Status",
        type: "select",
        multiple: false,
        data_list: [
            { label: "Pending Payment",   value: "pending_payment"   },
            { label: "Payment Submitted", value: "payment_submitted" },
            { label: "Payment Verified",  value: "payment_verified"  },
            { label: "In Progress",       value: "in_progress"       },
            { label: "Access Sent",       value: "access_sent"       },
            { label: "Completed",         value: "completed"         },
            { label: "Cancelled",         value: "cancelled"         },
            { label: "Refunded",          value: "refunded"          },
        ],
        value: "pending_payment",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "delivery_method",
        label: "Delivery Method",
        type: "select",
        multiple: false,
        data_list: [
            { label: "Email",          value: "email"          },
            { label: "WhatsApp",       value: "whatsapp"       },
            { label: "Manual Contact", value: "manual_contact" },
        ],
        value: "",
        is_visible: true,
        class: "col-md-6",
    },

    // ── Admin ─────────────────────────────────────────────────────────────────
    {
        name: "ref_code",
        label: "Reference Code",
        type: "text",
        value: "",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "order_number",
        label: "Order Number",
        type: "text",
        value: "",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "ordered_at",
        label: "Ordered At",
        type: "datetime-local",
        value: "",
        is_visible: true,
        class: "col-md-6",
    },

    // ── Text areas (always last) ──────────────────────────────────────────────
    {
        name: "project_description",
        label: "Project Description",
        type: "textarea",
        rows: 4,
        value: "",
        is_visible: true,
        class: "col-md-12",
    },
    {
        name: "special_requirements",
        label: "Special Requirements",
        type: "textarea",
        rows: 3,
        value: "",
        is_visible: true,
        class: "col-md-12",
    },
    {
        name: "admin_note",
        label: "Admin Note",
        type: "textarea",
        rows: 3,
        value: "",
        is_visible: true,
        class: "col-md-12",
    },
];
