/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "title",
		label: "Enter Title",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "asset_category_id",
		label: "Select Asset Category",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "description",
		label: "Enter Description",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "price",
		label: "Enter Price",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "memo_no",
		label: "Enter Memo No",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "memo_date",
		label: "Enter Memo Date",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "code",
		label: "Enter Code",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "asset_location",
		label: "Enter Asset Location",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "asset_owner",
		label: "Enter Asset Owner",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "owner_phone_number",
		label: "Enter Owner Phone Number",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "depreciation_amount",
		label: "Enter Depreciation Amount",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "depreciation_type",
		label: "Select Depreciation Type",
		type: "select",
		label: "Select Depreciation Type",
		multiple: false,
		data_list: [
			{ label: "Percent", value: "percent" },
			{ label: "Flat", value: "flat" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
