/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "name",
		label: "Enter Name",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "email",
		label: "Enter Email",
		type: "email",
		placeholder: "example@domain.com",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "phone",
		label: "Enter Phone",
		type: "tel",
		placeholder: "+1 (555) 000-0000",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "address",
		label: "Enter Address",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "nid_or_passport",
		label: "Enter Nid Or Passport",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "type",
		label: "Select Type",
		type: "select",
		label: "Select Type",
		multiple: false,
		data_list: [
			{ label: "Individual", value: "individual" },
			{ label: "Company", value: "company" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "equity_percentage",
		label: "Enter Equity Percentage",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "note",
		label: "Enter Note",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "joined_at",
		label: "Enter Joined At",
		type: "date",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "status",
		label: "Select Status",
		type: "select",
		label: "Select Status",
		multiple: false,
		data_list: [
			{ label: "Active", value: "active" },
			{ label: "Exited", value: "exited" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
