/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "transaction_log_id",
		label: "Select Transaction Log",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "recipient_type",
		label: "Select Recipient Type",
		type: "select",
		label: "Select Recipient Type",
		multiple: false,
		data_list: [
			{ label: "Division", value: "division" },
			{ label: "Branch", value: "branch" },
			{ label: "Division_member", value: "division_member" },
			{ label: "Others", value: "others" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "recipient_id",
		label: "Select Recipient",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "recipient_name",
		label: "Enter Recipient Name",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "amount",
		label: "Enter Amount",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "amount_in_text",
		label: "Enter Amount In Text",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "given_date",
		label: "Enter Given Date",
		type: "date",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "purpose",
		label: "Enter Purpose",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "payment_status",
		label: "Select Payment Status",
		type: "select",
		label: "Select Payment Status",
		multiple: false,
		data_list: [
			{ label: "Due", value: "due" },
			{ label: "Partial", value: "partial" },
			{ label: "Paid", value: "paid" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
