/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "client_name",
		label: "Enter Client Name",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "client_company",
		label: "Enter Client Company",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "media_type",
		label: "Select Media Type",
		type: "select",
		label: "Select Media Type",
		multiple: false,
		data_list: [
			{ label: "Image", value: "image" },
			{ label: "Video", value: "video" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "client_photo",
		label: "Upload Client Photo",
		type: "file",
		multiple: false,
		accept: "image/*",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "video_url",
		label: "Enter Video Url",
		type: "url",
		placeholder: "https://example.com",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "product_id",
		label: "Select Product",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "rating",
		label: "Enter Rating",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "message",
		label: "Enter Message",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "is_featured",
		label: "Select Is Featured",
		type: "select",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "1" },
			{ label: "No", value: "0" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "is_visible",
		label: "Select Is Visible",
		type: "select",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "1" },
			{ label: "No", value: "0" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
