/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "investor_id",
		label: "Select Investor",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "account_id",
		label: "Select Account",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "round",
		label: "Enter Round",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "amount",
		label: "Enter Amount",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "currency",
		label: "Enter Currency",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "type",
		label: "Select Type",
		type: "select",
		label: "Select Type",
		multiple: false,
		data_list: [
			{ label: "Equity", value: "equity" },
			{ label: "Loan", value: "loan" },
			{ label: "Grant", value: "grant" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "interest_rate",
		label: "Enter Interest Rate",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "agreement_date",
		label: "Enter Agreement Date",
		type: "date",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "received_at",
		label: "Enter Received At",
		type: "date",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "agreement_doc",
		label: "Upload Agreement Doc",
		type: "file",
		multiple: false,
		accept: "image/*,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "note",
		label: "Enter Note",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-12",
	},
];
