/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "product_group_id",
		label: "Select Product Group",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "name",
		label: "Enter Name",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "slug",
		label: "Enter Slug",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "description",
		label: "Enter Description",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "status",
		label: "Select Status",
		type: "select",
		label: "Select Status",
		multiple: false,
		data_list: [
			{ label: "Planning", value: "planning" },
			{ label: "Development", value: "development" },
			{ label: "Active", value: "active" },
			{ label: "Paused", value: "paused" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "launch_date",
		label: "Enter Launch Date",
		type: "date",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "monthly_target_revenue",
		label: "Enter Monthly Target Revenue",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "regular_price",
		label: "Regular Price",
		type: "number",
		step: "0.01",
		placeholder: "0.00",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "sales_price",
		label: "Sales Price",
		type: "number",
		step: "0.01",
		placeholder: "0.00",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "features",
		label: "Enter Features",
		type: "textarea",
		rows: 6,
		placeholder: "Enter valid JSON",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "screenshots",
		label: "Upload Screenshots",
		type: "file",
		multiple: true,
		accept: "image/*",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
